#pragma once

#include "audio/beat_patterns/chachacha.h"
#include "audio/beat_patterns/closer.h"
#include "audio/beat_patterns/conga.h"
#include "audio/beat_patterns/disco1.h"
#include "audio/beat_patterns/disco2.h"
#include "audio/beat_patterns/fiddy.h"
#include "audio/beat_patterns/florian.h"
#include "audio/beat_patterns/hiphop1.h"
#include "audio/beat_patterns/mickey.h"
#include "audio/beat_patterns/procession.h"
#include "audio/beat_patterns/reggae.h"
#include "audio/beat_patterns/shuffle.h"
#include "audio/beat_patterns/twist.h"
