// #include "mains/AudioSenderTest.cpp"
// #include "mains/audioSlave.cpp"
// #include "mains/audioTest.cpp"
// #include "mains/ButtonMatrixTest.cpp"
// #include "mains/ButtonTest.cpp"
// #include "mains/GliderWars.cpp"
// #include "mains/HeadToHead.cpp"
// #include "mains/LifeGame.cpp"
// #include "mains/main.cpp"
// #include "mains/RandomTest.cpp"
// #include "mains/RawMatrixTest.cpp"
// #include "mains/RhythmGame.cpp"
// #include "mains/RocketGame.cpp"
// #include "mains/WavManagerTest.cpp"
// #include "mains/synthest1.cpp"
// #include "mains/TwentyTest.cpp"
// #include "mains/SynthReciever.cpp"
#include "mains/SynthSender.cpp"

// Serial test programs
// #include "mains/serial/EZReceiverTest.cpp"
// #include "mains/serial/EZTransmitterTest.cpp"
// #include "mains/serial/HardwareReceiverTest.cpp"
// #include "mains/serial/HardwareTransmitterTest.cpp"

// Pauls Synth Example Adapted
// #include "mains/PaulSynth.cpp"