// #include "mains/AudioSenderTest.cpp"
// #include "mains/audioSlave.cpp"
// #include "mains/audioTest.cpp"
// #include "mains/ButtonMatrixTest.cpp"
// #include "mains/ButtonTest.cpp"
// #include "mains/GliderWars.cpp"
// #include "mains/HeadToHead.cpp"
// #include "mains/LifeGame.cpp"
#include "mains/main.cpp"
// #include "mains/RandomTest.cpp"
// #include "mains/RawMatrixTest.cpp"
// #include "mains/RhythmGame.cpp"
// #include "mains/RocketGame.cpp"
// #include "mains/SerialReceiverTest.cpp"
// #include "mains/SlaveDriverTest.cpp"
// #include "mains/synthest1.cpp"
// #include "mains/TwentyTest.cpp"